name: Daily Telegram Report

on:
  schedule:
    - cron: "30 17 * * *"  # اجرای خودکار هر روز ساعت 21:00 تهران (17:30 UTC)
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests jdatetime beautifulsoup4 lxml html5lib

      - name: Build message (Jalali date + Market Data)
        run: |
          python .github/scripts/build_msg.py > message.txt

      - name: Send to Telegram
        run: |
          curl -sS -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\":\"${{ secrets.TELEGRAM_CHAT_ID }}\",\"text\":\"$(cat message.txt | sed 's/\"/\\"/g')\",\"parse_mode\":\"HTML\",\"disable_web_page_preview\":true}"
